### GET all notes
GET http://localhost:8080/notes

### POST a new note
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Note",
  "content": "Content",
  "author": "Author",
  "xPosition": 100,
  "yPosition": 20,
  "creationDate": ""
}

### GET a specific note
GET http://localhost:8080/notes/47

### DELETE a specific note
DELETE http://localhost:8080/notes/113

### PUT to update a specific note
PUT http://localhost:8080/notes/113
Content-Type: application/json

{
  "title": "TEST",
  "content": "Content",
  "author": "Author",
  "xPosition": 100,
  "yPosition": 20,
  "creationDate": ""
}